<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:property name="wheel_radius" value="0.031" />
  <xacro:property name="wheel_zoff" value="0.035" />

  <xacro:macro name="create_wheel_link"
    params="
        link_name
        mesh_name">
    <link name="${link_name}">
      <visual>
        <origin rpy="${pi / 2.0} 0 0" xyz="0 0 0" />
        <geometry>
          <mesh filename="${mesh_dir}/${mesh_name}.dae" />
        </geometry>
      </visual>
      <collision>
        <geometry>
          <!-- <sphere radius="0.035" /> -->
          <cylinder length="0.035" radius="${wheel_radius}" />
        </geometry>
      </collision>
      <inertial>
        <mass value="0.053774" />
        <inertia
          ixx="2.1E-05"
          iyy="2.1E-05"
          izz="3.3E-05"
          ixy="0.0"
          ixz="0.0"
          iyz="0.0" />
      </inertial>
    </link>
  </xacro:macro>

  <xacro:macro name="create_wheel_joint"
    params="
        joint_name
        link_name
        xyz_offset">
    <joint name="${joint_name}" type="continuous">
      <parent link="$(arg prefix)base_link" />
      <child link="${link_name}" />
      <origin rpy="${pi / -2.0} 0 0" xyz="${xyz_offset}" />
      <axis xyz="0 0 1" />
      <!-- <limit effort="3.9" velocity="36.92" /> -->
      <limit effort="10000.0" lower="-1.79769e+308" upper="1.79769e+308" velocity="15.1" />
    </joint>
  </xacro:macro>

  <xacro:create_wheel_link
    link_name="$(arg prefix)right_front_wheel_link"
    mesh_name="right_front">
  </xacro:create_wheel_link>

  <xacro:create_wheel_link
    link_name="$(arg prefix)left_front_wheel_link"
    mesh_name="left_front">
  </xacro:create_wheel_link>

  <xacro:create_wheel_link
    link_name="$(arg prefix)right_rear_wheel_link"
    mesh_name="right_rear">
  </xacro:create_wheel_link>

  <xacro:create_wheel_link
    link_name="$(arg prefix)left_rear_wheel_link"
    mesh_name="left_rear">
  </xacro:create_wheel_link>

  <xacro:create_wheel_joint
    joint_name="$(arg prefix)right_front_wheel_joint"
    link_name="$(arg prefix)right_front_wheel_link"
    xyz_offset="0.083 -0.081 -${wheel_zoff}"
  />
  <xacro:create_wheel_joint
    joint_name="$(arg prefix)left_front_wheel_joint"
    link_name="$(arg prefix)left_front_wheel_link"
    xyz_offset="0.083 0.079 -${wheel_zoff}"
  />
  <xacro:create_wheel_joint
    joint_name="$(arg prefix)right_rear_wheel_joint"
    link_name="$(arg prefix)right_rear_wheel_link"
    xyz_offset="-0.08 -0.081 -${wheel_zoff}"
  />
  <xacro:create_wheel_joint
    joint_name="$(arg prefix)left_rear_wheel_joint"
    link_name="$(arg prefix)left_rear_wheel_link"
    xyz_offset="-0.08 0.079 -${wheel_zoff}"
  />

  <link name="base_footprint" />
  <joint name="footprint_joint" type="fixed">
    <parent link="base_link" />
    <child link="base_footprint" />
    <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0" />
  </joint>
</robot>