controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    controller:
      type: mecanum_drive_controller/MecanumDriveController

controller:
  ros__parameters:
    reference_timeout: 0.1

    front_left_wheel_command_joint_name: "left_front_wheel_joint"
    front_right_wheel_command_joint_name: "right_front_wheel_joint"
    rear_left_wheel_command_joint_name: "left_rear_wheel_joint"
    rear_right_wheel_command_joint_name: "right_rear_wheel_joint" 

    kinematics:
      base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
      wheels_radius: 0.035
      sum_of_robot_center_projection_on_X_Y_axis: 0.16

    enable_odom_tf: false
    # base_frame_id: "base_link"
    # odom_frame_id: "odom"
    # twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    # pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
